### ISSUE TITLE
Jvm cannot be sent between threads. How can I work with invoke_async?

### ISSUE THREAD

**Issue by pickleburger** [astonbitecode/j4rs#103]
Hello,

Based on https://github.com/astonbitecode/j4rs/issues/72, Jvm cannot be sent between threads. In that case, how can I work with `invoke_async`? As soon as I call `await` on the future returned by `invoke_async`, I get the compilation error complaining that Jvm cannot be sent between threads. How can I work around it? Thanks!

Sample error message:
```
the trait `Send` is not implemented for `*mut *const JNINativeInterface_`, which is required by `{async block@src/main.rs:53:134: 76:6}: Send`
```

Sample code snippet

```rust
#[tonic::async_trait]
impl MyApi for MyApiService {

    async fn get(&self, request: Request<GetRequest>) -> Result<Response<GetResponse>, Status> {
        let Ok(jvm) = Jvm::attach_thread()
            else { return Err(Status::internal("attach_thread failed")) };
        let Ok(my_object) = jvm.invoke_static("com.example.MyObject", "getInstance", &Vec::<InvocationArg>::new())
            else { return Err(Status::internal("invoke_static failed")) };
        // let args = ...
        let _ = jvm.invoke_async(&my_object, "get", &vec![args]).await;

        // ...
        Ok(Response::new(GetResponse::default()))
    }
}
```

**Comment by astonbitecode** [comment]
As long as you do not use `jvm` later, it should not be a problem.
Remember that after `await`ing the execution thread changes and the `Jvm` should be attached to the new thread.

Unfortunately I cannot test it myself as I am currently on vacations, staying away from the keyboard..

**Comment by pickleburger** [comment]
It's probably due to tonic forcing the future to be `Send` by using `async_trait`, but I'm not 100% sure. Do you think that's a plausible explanation?

Also found some discussion here: https://github.com/hyperium/tonic/issues/844

**Comment by astonbitecode** [comment]
Ah, I believe I see the problem... The `Future` returned by `invoke_async` is not `Send` indeed... The reason is that the `Jvm` is used internally __after__ the Future is created in order to check for the possible errors of the invocation. 

This is fixable though and will deal with it in a few days.

Thanks for the report, this is a nice finding!

**Comment by pickleburger** [comment]
Awesome! Thanks for confirming! Looking forward to the fix.

**Comment by astonbitecode** [comment]
I took the time to test using async with tonic and unfortunately, there are more errors regarding `Send` for the `Future` returned by the `invoke_async`, additionally to the error message you mentioned... 

> This is fixable though and will deal with it in a few days.

This was an over-optimistic statement because I took as granted that the issue was only because of the internal reuse of the `Jvm` during the `invoke_async` execution and __after__ calling [`await`](https://github.com/astonbitecode/j4rs/blob/612a76229de72efb484f97b9e28f20acdf57ca44/rust/src/async_api/mod.rs#L105).

However, there are more errors, with the most important being:

```error[E0277]: `*mut *const JNINativeInterface_` cannot be shared between threads safely```

Even if the rest of the errors are somehow fixed, I guess we cannot do anything about this one... The reason is that by [jni specification](https://docs.oracle.com/en/java/javase/17/docs/specs/jni/design.html):

> The JNI interface pointer is only valid in the current thread. A native method, therefore, must not pass the interface pointer from one thread to another.

So, I believe by JNI definition, the `Future` returned by j4rs can never be `Send`.

**Comment by astonbitecode** [comment]
Taking a step back though, I cannot fully understand why we get the compilation error, that is, why the block before `await` must be also `Send`... 

For example, in the code snippet you provided, could the execution be stopped at line:

```rust
let Ok(jvm) = Jvm::attach_thread()
            else { return Err(Status::internal("attach_thread failed")) };
```

and then continue from line:
```rust
let Ok(my_object) = jvm.invoke_static("com.example.MyObject", "getInstance", &Vec::<InvocationArg>::new())
            else { return Err(Status::internal("invoke_static failed")) };
```

in another thread? 

I thought this execution is not interrupted... What do I miss?

**Comment by pickleburger** [comment]
> I thought this execution is not interrupted

Yes, you are correct. I don't think the execution is interrupted after either `attach_thread` or `invoke_static`. It's interrupted when `await`ing the future returned from `invoke_async`.

I also thought about how to fix it. I have a strong feeling that we need to implement the future manually, instead of relying on `async fn` to generate it for us. I'll look deeper into it probably in the coming weekend.

**Comment by astonbitecode** [comment]
It seems that with a bit of "scoping" and "moving" we can have the `Future + Send` we need.

I implemented a function `invoke_into_sendable_async` in `Jvm` that does not take a `Jvm` input (either as argument or as self reference) and consumes all its arguments.

1. No `Jvm` input because it seems that `Jvm` must not be in scope while `await`ing the future.
2. Consumes all its arguments because neither `&Instance` not `&[InvocationArg]` are `Send`

According to the above, your example should compile like:

```rust
#[tonic::async_trait]
impl MyApi for MyApiService {

    async fn get(&self, request: Request<GetRequest>) -> Result<Response<GetResponse>, Status> {
    	
        let (my_object, args) = {
            let Ok(jvm) = Jvm::attach_thread() else {
                return Err(Status::internal("attach_thread failed"));
            };
            let Ok(my_object) = jvm.invoke_static(
                "com.example.MyObject",
                "getInstance",
                &Vec::<InvocationArg>::new(),
            ) else {
                return Err(Status::internal("invoke_static failed"));
            };
            let args: Vec<InvocationArg> = vec![
                InvocationArg::try_from("a_string").unwrap(),
                InvocationArg::try_from(3).unwrap(),
                // ...
            ];
            (my_object, args)
        };

        let _ = Jvm::invoke_into_sendable_async(my_object, "get".to_string(), args).await;

        // ...
        Ok(Response::new(GetResponse::default()))
    }
}
```

Thoughts:

* The `Jvm::invoke_into_sendable_async` implicitly invokes `Jvm::attach_thread` twice... Once before the `await` and one after. This _may_ have performance penalty. If this is not good for you, you may think if it is better to use `Jvm` via other means, like message-passing/Actors etc
* This whole `Send` story made me started thinking whether it is correct to mark `&Instance` as `Send`. Such thing would make `Instance` to be `Sync`. If this happens, we could have the api of `Jvm::invoke_into_sendable_async` accepting references instead of moving values
* I still have the feeling that the compiler is needlessly strict in our case. This needed scoping tricks may be the proof.

**Comment by pickleburger** [comment]
Thanks for putting up the quick fix! I was thinking about manually creating the future so that even if we pass `Jvm` and `Instance` as references, they are not necessarily captured in the future. But such implementation could be tricky. Your approach also works.

However, I think there is an issue in the implementation. I put up a PR here https://github.com/astonbitecode/j4rs/pull/104.

Making Instances Send could be useful if we want to reuse the object after awaiting the future.

Yeah, if the compiler can deduce that the non-sendable variables are never used across await, it would make our life lot easier. It seems we have to do manual scoping today. The trick is also described in https://rust-lang.github.io/async-book/07_workarounds/03_send_approximation.html. Sad :(

In terms of performance, it might be Ok to attach the thread twice. I'm not sure how much penalty we will hit. I think we need some benchmarking to get some idea. However, I checked the Java part and I'm concerned about the use of Stream APIs. Based on my past experience, they are bad for GC and CPU. Given `j4rs` is a low-level library, I think it's worthwhile to optimize for the performance at the sacrifice of "stylish code". I can put up some PRs to migrate them to the old-school loops, if you agree with that statement :).

**Comment by pickleburger** [comment]
> ~~Making Instances Send could be useful if we want to reuse the object after awaiting the future~~

Sorry, I misread your comment. I saw that `Instance` was already marked as Send.

**Comment by pickleburger** [comment]
Sounds good. Thanks for addressing the issue! Feel free to close it.

**Comment by pickleburger** [comment]
BTW, when do you think you can release this new feature?

**Comment by astonbitecode** [comment]
There is no specific schedule. I can create a new release today or tomorrow.
