### ISSUE TITLE
Can Jvm support lazy_static ？

### ISSUE THREAD

**Issue by zhengxiwan** [astonbitecode/j4rs#14]
eg:
```
   lazy_static::lazy_static! {
        static ref JAVA_JVM:Jvm={
             JvmBuilder::new().build().unwrap()
        };
    }
```

**Comment by astonbitecode** [comment]
Each Jvm must be used by one thread as defined by the [jni specs](https://docs.oracle.com/javase/9/docs/specs/jni/invocation.html#attaching-to-the-vm): 

> The JNI interface pointer (JNIEnv) is valid only in the current thread. Should another thread need to access the Java VM, it must first call AttachCurrentThread() to attach itself to the VM and obtain a JNI interface pointer.

Should you try to create a Jvm in lazy_static, it would mean that the Jvm is accessible from many threads. This cannot be done, because Jvm contains a `JNIEnv` pointer...

However, I guess you may store a Jvm in [thread_local storage](https://doc.rust-lang.org/std/macro.thread_local.html). I haven't tried it myself, but I don't see why it would not be possible.
