### ISSUE TITLE
Need help understanding Automatic/manual class path resolution

### ISSUE THREAD

**Issue by jtmorrisbytes** [astonbitecode/j4rs#17]
I am having difficulty setting up a project to use a library jar from a class that uses rust channels as per the example. There seems to be no documentation on how your automatic class path resolution works, or how to manually resolve class paths. also, since I am still somewhat new to building java libraries, it is unclear how I should build my library, and where I should place my jars ( including folder structure), and how I should structure my class identifiers. It would be helpful to direct users to some resources that would constitute a basic tutorial.

**Comment by astonbitecode** [comment]
There are two ways to add a jar in the classpath:

1. [Defining a path](https://github.com/astonbitecode/j4rs#adding-jars-to-the-classpath)
(Please, take into consideration possible [classpath definition](https://stackoverflow.com/questions/16502663/java-classpath-and-relative-paths) issues).
2. [Using Maven](https://github.com/astonbitecode/j4rs#using-maven-artifacts)

For a complete example, there is the [j4rs-showcase](https://github.com/astonbitecode/j4rs-showcase), where you can see the definition of a [classpath entry](https://github.com/astonbitecode/j4rs-showcase/blob/dbcac652155d4e35479ecd13b7c82b3aaaf02ed1/rust/src/main.rs#L13) and the [callback definition](https://github.com/astonbitecode/j4rs-showcase/blob/dbcac652155d4e35479ecd13b7c82b3aaaf02ed1/rust/src/main.rs#L36).

Regarding the folder structure of your project, there is no limitation or any need for j4rs, as long as you use these two methods above to define the classpath. 

If you still have issues, please describe how you are trying to do the callback, or, if possible, share a link of your project in order to have a look.

**Comment by jtmorrisbytes** [comment]
It was a bundling/ configuration issue on my part
