### ISSUE TITLE
jassets required to instantiate Jvm?

### ISSUE THREAD

**Issue by Heliozoa** [astonbitecode/j4rs#19]
Hi, I'm trying to make a binary crate that depends on j4rs. It worked fine when running it through cargo but when trying to use the binary it would error out with a vague "entity not found". Turned out this error was coming from fs_extras hitting broken symlinks or files owned by root while looking everywhere for the jassets directory at the `get_dir_content` call at
https://github.com/astonbitecode/j4rs/blob/e1ee32e469a6598b46dc5940540ffdb2606646a7/rust/src/utils.rs#L88-L91
The binary works fine if I copy the jassets directory to the same directory as the binary. Should I just bundle the jar in jassets with the binary? Sorry if I've misunderstood something, and thanks for your work on j4rs!

**Comment by astonbitecode** [comment]
Indeed, the jassets directory is needed for j4rs to work, because it contains the "java world". You may consider it something like a default classpath container that should always be available.

However, you may specify the [base_path](https://docs.rs/j4rs/0.11.2/j4rs/struct.JvmBuilder.html#method.with_base_path) for j4rs during the Jvm initialization, issuing something like:

```rust
let jvm_res = j4rs::JvmBuilder::new()
        .with_base_path(&base_path_string)
        .build();
```

As you can see in the documentation, the base_path defines the location of the jassets and deps directories. 

1. __jassets__ contains the j4rs jar and other jars that may be deployed using [Maven](https://github.com/astonbitecode/j4rs#Using-Maven-artifacts).
2. __deps__ contains the j4rs dynamic library. This is needed to achieve  [callbacks](https://github.com/astonbitecode/j4rs#Callback-support) from java to rust. For more details on callbacks, you may have a look at the [j4rs-showcase](https://github.com/astonbitecode/j4rs-showcase). You don't need the deps dir if Your application does not need Java->Rust callbacks.

**Comment by Heliozoa** [comment]
Got it, thanks! I was able to make it work with a similar setup to what you described.

**Comment by schmidmt** [comment]
Hi @astonbitecode, it seems this behavior isn't really mentioned anywhere in the docs or the README, and instead of getting a reasonable error about missing assets we get an `Error { kind: Other, message: \"Too many levels of symbolic links (os error 40)\" }` from the library traversing `/proc` where it encounters a loop. 

For usability's sake, it might be a good idea to document this non-portability and handle the error condition where this occurs.

**Comment by astonbitecode** [comment]
You are right, @schmidmt... I am adding a description to try to make things clear.

Thanks for the suggestion.

**Comment by evbo** [comment]
What if we don't have write permission to `/opt`? What is the recommended process for bundling jassets with the binary?

**Comment by astonbitecode** [comment]
You may define any directory you want. 

Please have a  look in the [README](https://github.com/astonbitecode/j4rs?tab=readme-ov-file#portability-assumptions-after-rust-build-shipping-a-j4rs-application) for more details.

**Comment by astonbitecode** [comment]
Yes you may place the JRE in any place you want and just define the `JAVA_HOME` to point to its location. `j4rs` will pick  it up and use it as normal.
