### ISSUE TITLE
How do we get the package for Java

### ISSUE THREAD

**Issue by owen-hope** [astonbitecode/j4rs#20]
Hi I have been looking through the examples you have and I haven't be able to see where we would go about getting the package that is required for callbacks on the Java end of things.

Is there any instruction on this?

**Comment by astonbitecode** [comment]
The j4rs jars can be found in maven central. You may get them using [maven](https://github.com/astonbitecode/j4rs#j4rs-java-library), gradle etc, or even [download them](http://search.maven.org/classic/#search%7Cgav%7C1%7Cg%3A%22io.github.astonbitecode%22%20AND%20a%3A%22j4rs%22) and manually add them in your classpath.

Please take care to use the same version with the j4rs Rust crate that you use in order to be sure that you will not have issues.

**Comment by astonbitecode** [comment]
I guess this can be closed now...

**Comment by evbo** [comment]
Where are complete examples? Or is it just the snippets listed in the readme?

**Comment by astonbitecode** [comment]
There are examples for several use cases. If you read the README you may find references and links for them. 

For example:

* An example of an application written in Rust, creating a JavaFX UI - https://github.com/astonbitecode/j4rs-showcase
* An example of a Java application that calls a Rust library - https://github.com/astonbitecode/j4rs-java-call-rust
* An example of an Android application calling a Rust library - https://github.com/astonbitecode/j4rs-android-test
* An example of an Android application runninf in Rust only, using Android Activity crate - https://github.com/astonbitecode/j4rs-android-activity

**Comment by evbo** [comment]
This is an awesome summary, thank you. Blame on my ADD but I literally read it and breezed past see these references :D
