### ISSUE TITLE
How to enable sanitizer?

### ISSUE THREAD

**Issue by wangxiaoying** [astonbitecode/j4rs#40]
I'm writing a library with `j4rs` and it works great! However when I try to enable sanitizer following [this instruction](https://doc.rust-lang.org/beta/unstable-book/compiler-flags/sanitizer.html#addresssanitizer) it shows the following error:

```
java.lang.UnsatisfiedLinkError: /home/ubuntu/j4rs-sanitizer-example/target/x86_64-unknown-linux-gnu/debug/deps/libj4rs_sanitizer_example.so: /home/ubuntu/j4rs-sanitizer-example/target/x86_64-unknown-linux-gnu/debug/deps/libj4rs_sanitizer_example.so: undefined symbol: __asan_option_detect_stack_use_after_return
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2662)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at org.astonbitecode.j4rs.api.invocation.NativeCallbackToRustChannelSupport.initialize(NativeCallbackToRustChannelSupport.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeMethod(JsonInvocationImpl.java:179)
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeStatic(JsonInvocationImpl.java:80)
Tracer caught signal 11: addr=0x100000680 pc=0x55d076488f8a sp=0x7f843728ed40
==28056==LeakSanitizer has encountered a fatal error.
==28056==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==28056==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc
```

I'm running the code on a ubuntu instance, and here is a simple example code to reproduce: https://github.com/wangxiaoying/j4rs-sanitizer-example

Error occurs as long as jvm has been initiated.

**Comment by astonbitecode** [comment]
The error is thrown while `j4rs` tries to initialize the callbacks from Java. 

Do  you use [Java callbacks](https://github.com/astonbitecode/j4rs#Callback-support)? If not, I guess the easiest thing to do is to call `skip_setting_native_lib` during the `Jvm` creation:

```rust
let jvm: Jvm = JvmBuilder::new().skip_setting_native_lib().build().unwrap();
```

**Comment by wangxiaoying** [comment]
Hi @astonbitecode , thanks for the reply.

The `UnsatisfiedLinkError` is indeed caused by the callbacks and can be eliminated by calling `skip_setting_native_lib`. However, the sanitizer error still exists as long as jvm is initiated (no matter load an existing jar file or not):

```
$ RUSTFLAGS=-Zsanitizer=address cargo run --example init_naive_jvm -Zbuild-std --target x86_64-unknown-linux-gnu
   Compiling j4rs_sanitizer_example v0.1.0 (/home/ubuntu/j4rs-sanitizer-example)
    Finished dev [unoptimized + debuginfo] target(s) in 1.37s
     Running `target/x86_64-unknown-linux-gnu/debug/examples/init_naive_jvm`
Tracer caught signal 11: addr=0x100000590 pc=0x561af17ccf8a sp=0x7f2b5215fd40
==8775==LeakSanitizer has encountered a fatal error.
==8775==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==8775==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)

$ RUSTFLAGS=-Zsanitizer=address cargo run --example init_jvm -Zbuild-std --target x86_64-unknown-linux-gnu
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/x86_64-unknown-linux-gnu/debug/examples/init_jvm`
Tracer caught signal 11: addr=0x100000598 pc=0x55875d857f8a sp=0x7f3f5972ad40
==8846==LeakSanitizer has encountered a fatal error.
==8846==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==8846==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
```

I have updated the examples in https://github.com/wangxiaoying/j4rs-sanitizer-example, you can reproduce the above errors using `init_naive_jvm` (do not load jar) and `init_jvm` (load jar).

**Comment by astonbitecode** [comment]
I am not familiar with sanitizers, but it seems that something goes wrong with executing it. I guess that when there is a leak, the errors are more descriptive, so I am not sure if it is indeed a leak indication, but would like to be sure about it.

I am investigating a bit deeper...

**Comment by astonbitecode** [comment]
The sanitizer crash issue seems to be because  the `libjvm.so` is loaded dynamically, so the sanitizer does not know how to handle it when the application calls its symbols. 

Using `LD_PRELOAD` to make `libjvm.so` visible to the sanitizer resolves the crashing issue (Tracer caught signal 11) but generates a lot of presumably false positive leaks.

I use Java 17, so, running:

```
LD_PRELOAD=/usr/lib/jvm/java-17-openjdk-amd64/lib/server/libjvm.so RUSTFLAGS=-Zsanitizer=address cargo run --example init_naive_jvm -Zbuild-std --target x86_64-unknown-linux-gnu
```

Produces big output like:

```
Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x5615c7f45cbe  (/home/aston/git/j4rs-sanitizer-example/target/x86_64-unknown-linux-gnu/debug/examples/init_naive_jvm+0x1c7cbe) (BuildId: 0db5eae9d473a6058d21b46c237e37a1b9042376)
    #1 0x7fdbbd755a68  (/usr/lib/jvm/java-17-openjdk-amd64/lib/server/libjvm.so+0x3cea68) (BuildId: 4739309bcbed62473d95f7d3ca55182a9bd30f9b)
    #2 0x7fdbbdb9b9b1  (/usr/lib/jvm/java-17-openjdk-amd64/lib/server/libjvm.so+0x8149b1) (BuildId: 4739309bcbed62473d95f7d3ca55182a9bd30f9b)
    #3 0x7fdbbdc5048f  (/usr/lib/jvm/java-17-openjdk-amd64/lib/server/libjvm.so+0x8c948f) (BuildId: 4739309bcbed62473d95f7d3ca55182a9bd30f9b)
    #4 0x7fdbbc691f61  (/usr/lib/jvm/java-17-openjdk-amd64/lib/libjava.so+0x12f61) (BuildId: 60188287aa65254c60e51a1474ef9a796260be5d)
...
...
...
Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x5615c7f45cbe  (/home/aston/git/j4rs-sanitizer-example/target/x86_64-unknown-linux-gnu/debug/examples/init_naive_jvm+0x1c7cbe) (BuildId: 0db5eae9d473a6058d21b46c237e37a1b9042376)
    #1 0x7fdbbd755a68  (/usr/lib/jvm/java-17-openjdk-amd64/lib/server/libjvm.so+0x3cea68) (BuildId: 4739309bcbed62473d95f7d3ca55182a9bd30f9b)
    #2 0x7fdbbdb9b9b1  (/usr/lib/jvm/java-17-openjdk-amd64/lib/server/libjvm.so+0x8149b1) (BuildId: 4739309bcbed62473d95f7d3ca55182a9bd30f9b)
    #3 0x7fdbbdc5048f  (/usr/lib/jvm/java-17-openjdk-amd64/lib/server/libjvm.so+0x8c948f) (BuildId: 4739309bcbed62473d95f7d3ca55182a9bd30f9b)
    #4 0x7fdbbc691fd1  (/usr/lib/jvm/java-17-openjdk-amd64/lib/libjava.so+0x12fd1) (BuildId: 60188287aa65254c60e51a1474ef9a796260be5d)
    #5 0x7fdba304d4b9  (<unknown module>)
    #6 0x7fdba304923d  (<unknown module>)
    #7 0x7fdba3040cc8  (<unknown module>)
...
...
...

SUMMARY: AddressSanitizer: 18028 byte(s) leaked in 456 allocation(s).
```

As you can see, the indicated leaks are in the `libjvm` only. 

I assume they are there because of the way that the library is loaded:
when the library is added in the `LD_PRELOAD`,  the symbols are found by the sanitizer and it is not crashing... However. the library is preloaded, even _before_ the sanitizer and maybe this is the issue. 

I tried to manually add the sanitizer as well in the `LD_PRELOAD`(before the libjvm):

```
LD_PRELOAD=/usr/lib/llvm-10/lib/clang/10.0.0/lib/linux/libclang_rt.asan-x86_64.so:/usr/lib/jvm/java-17-openjdk-amd64/lib/server/libjvm.so RUSTFLAGS=-Zsanitizer=address cargo run --example init_naive_jvm -Zbuild-std --target x86_64-unknown-linux-gnu
```

but I do not know which sanitizer is used by cargo, so I am getting:

> ==160755==Your application is linked against incompatible ASan runtimes.

I cannot find any asan library in the rust libraries, so I am not sure how to proceed.

One more reason I believe the indicated leaks are false positives, is that I tried to create multiple `Jvm`s in a loop eg in the `init_naive_jvm.rs` and the "leaked" bytes are the same no matter if the created `Jvm`s are 1, 2 or 10...

Creating 1 `Jvm` gives the output:
> SUMMARY: AddressSanitizer: 18028 byte(s) leaked in 456 allocation(s).

Creating 5:
> SUMMARY: AddressSanitizer: 18028 byte(s) leaked in 456 allocation(s).

Creating 10:
> SUMMARY: AddressSanitizer: 18028 byte(s) leaked in 456 allocation(s).

**Comment by wangxiaoying** [comment]
Thank you! I will also try on my machine to see whether I can load the correct sanitizer.

**Comment by astonbitecode** [comment]
So I managed to run the sanitizer using the following command:

```
LSAN_OPTIONS="suppressions=/path/to/asan.supp" LD_PRELOAD="/usr/lib/jvm/java-17-openjdk-amd64/lib/server/libjvm.so" ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer-10 RUSTFLAGS="-Zsanitizer=address" cargo run --example init_naive_jvm -Zbuild-std --target x86_64-unknown-linux-gnu
```

Explaining the env vars used:

* __LSAN_OPTIONS__: The reported leaks from `libjvm` can be suppressed in order to keep the findings clean. This can be done by creating a suppressions file (eg. asan.supp) with the following content:

```
leak:openjdk
```
Specify the file in the `LSAN_OPTIONS` env var. I use `openjdk` and this is why the suppression can be defined like this. You may find more details on suppression definition [here](https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer#suppressions).

* __LD_PRELOAD__: Define the `jvm` shared library in order for the sanitizer to find its symbols and not crash

* __ASAN_SYMBOLIZER_PATH__: Needed to provide readable output when leaks are found.

The sanitizer works nicely having this setup. 

It also found a leak in the `j4rs` initialization! The leak was during the `vm_options` definition, where `c_string`s are used, but the deallocation was not done correctly. This is now fixed and will be pushed shortly, but, honestly I doubt that I could find it without ASAN, since it was an allocation that was done wrongly only once during the application lifecycle.

Thank you for indicating the sanitizer, I guess now we can use it with `j4rs`!

**Comment by wangxiaoying** [comment]
That's awesome, thank you so much for digging in this issue! Looking forward to the release of 0.14.1 : )
