### ISSUE TITLE
Not compatible with java 8

### ISSUE THREAD

**Issue by lifan-ake** [astonbitecode/j4rs#54]
I believe the j4rs v0.15.3's jar package is dependent with logback v1.4.x which is compiled by Java major version 55. So I cannot use it with jdk 1.8. Is this version designed to not compatible with Java 8?

**Comment by astonbitecode** [comment]
> Is this version designed to not compatible with Java 8?

Not intentionally... `logback` was upgraded to 1.4.x in `j4rs` version `0.15.0`, mainly for security issues.

Honestly I didn't realize that it is not compatible with Java 8, neither investigated it since it would be (and is now) end of life. 

I see we can use the logback 1.3.x branch that supports Java8 still (it [seems](https://logback.qos.ch/news.html) they will be supporting it for a while). 

Will push a commit for it soon to give it a try. However, beware that there are parts of `j4rs` that require Java versions higher than 8 (like eg. the enhanced classloader).

Thanks for the report.

**Comment by astonbitecode** [comment]
Ok the commit is on master. Can you please give it a try?

Please note that you will need to use `JvmBuilder::with_default_classloader` to work with Java 8. Eg:

`let jvm = JvmBuilder::new().with_default_classloader().build();`

**Comment by lifan-ake** [comment]
Sorry for the late reply. I've tried the master version. It works for java 8 right now. Thx.
