### ISSUE TITLE
Invoking java methods asynchronously

### ISSUE THREAD

**Issue by WillyKidd** [astonbitecode/j4rs#56]
I am wondering how to invoke java methods asynchronously...For example, in the following function, I wish to `await` on the result of `invoke` (which invokes the method `getChunk` on the instance)
```rust
pub struct InstanceWrapper {
    pub inner: Instance,
}

unsafe impl Send for InstanceWrapper {}
unsafe impl Sync for InstanceWrapper {}

pub async fn get_cdc_chunk(&self, dbz_handler: &InstanceWrapper) -> GetEventStreamResponse {
    let res_java = self
        .jvm
        .invoke(&dbz_handler.inner, "getChunk", vec![].as_slice())
        .await
        .unwrap();
    self.jvm.to_rust(res_java).unwrap()
}
```
The compiler gives the following error
```
error[E0277]: `std::result::Result<j4rs::Instance, j4rs::errors::J4RsError>` is not a future
   --> src/connector/src/jvm_utils.rs:112:13
    |
112 |             .await
    |             ^^^^^^
    |             |
    |             `std::result::Result<j4rs::Instance, j4rs::errors::J4RsError>` is not a future
    |             help: remove the `.await`
    |
    = help: the trait `futures::Future` is not implemented for `std::result::Result<j4rs::Instance, j4rs::errors::J4RsError>`
    = note: std::result::Result<j4rs::Instance, j4rs::errors::J4RsError> must be a future or must implement `IntoFuture` to be awaited
    = note: required for `std::result::Result<j4rs::Instance, j4rs::errors::J4RsError>` to implement `std::future::IntoFuture`
```
I am wondering whether it would be possible to invoke it asynchronously...or should I consider using `invoke_to_channel` instead?

**Comment by astonbitecode** [comment]
Async is not yet supported in `j4rs` with the form of `Future`s. 

As you understood, the `invoke_to_channel` is currently the only way to achieve asychronous calls.

Just to note that in a future `j4rs` release, it is considered that Java Futures will be mapped to Rust Futures and therefore the caller will be able to `await` on them.

**Comment by StrikeW** [comment]
> Async is not yet supported in `j4rs` with the form of `Future`s.
> 
> As you understood, the `invoke_to_channel` is currently the only way to achieve asychronous calls.
> 
> Just to note that in a future `j4rs` release, it is considered that Java Futures will be mapped to Rust Futures and therefore the caller will be able to `await` on them.

Looking forward to it. And I found that `Instance` is not `Send` and `Sync` so that prevent it to across await point. For example, invoke a method on the instance after an `await` point.

**Comment by astonbitecode** [comment]
Hi @StrikeW ,

> And I found that Instance is not Send and Sync

Instance [is `Send`](https://github.com/astonbitecode/j4rs/blob/d74c8fb92071d36229d8404022a662c724fdeb8c/rust/src/api/instance.rs#L128) and can be sent to other threads, but is not `Sync`.  We need closer investigation to see whether this restriction can be dropped...

However, the `Jvm` is not even `Send`, because the underlying JNI `JNIEnv`  needs to be [attached to a thread](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html#attaching_to_the_vm).

I hope I will shortly start implementing this feature and see where it gets.

**Comment by astonbitecode** [comment]
Implemented `.async/.await` support for the Rust->Java direction. 

Please see the [README](https://github.com/astonbitecode/j4rs#Async-support) for some details.

**Comment by WillyKidd** [comment]
Cannot wait to try this new feature! Can I know when version 16.0 will be released?

**Comment by astonbitecode** [comment]
We just need a bit of testing and it will be released in a few days I guess.

It would be very useful if you used the master branch to give it a try before releasing; it would help finding issues earlier. 

You may define in your Cargo.toml the `j4rs` dependency as following:

```toml
j4rs = {git = "https://github.com/astonbitecode/j4rs.git"}
```

**Comment by astonbitecode** [comment]
v0.16.0 is published. Closing...

**Comment by evbo** [comment]
So does this mean polling is necessary for situations where callbacks are used in the Java code rather than `Future`? In other words, there's no way for rust and java to call each other bidirectionally?

For example, this sort of bidirectional calling isn't possible is it?

- rust calls java func synchronously
- java func [registers callback with remote server](https://github.com/perforce/p4java-examples/blob/master/examples/example-project/src/com/perforce/exampleproject/ListFilesDemo.java#L38)
- java func pings remote server
- remote server executes java callback
- java callback calls rust with result

**Comment by astonbitecode** [comment]
@evbo you can do this with `j4rs` using callbacks. 

Please see [here](https://github.com/astonbitecode/j4rs?tab=readme-ov-file#callback-support) for details.

**Comment by evbo** [comment]
Wait... I get it - just *read* the readme

**Comment by evbo** [comment]
Thank you @astonbitecode but can a single rust callback be called multiple times? How would that look in the rust code? Could I just put a while loop, something like?:

```rust
while {
    let instance_receiver = instance_receiver_res?;
    let val = instance_receiver.rx().recv();
    // break if val == 0, etc.
}
```

**Comment by astonbitecode** [comment]
Yes. Java may use the callback many times and in Rust you may have a loop as you expect and get the invocations from Java as messages from the receiver.

**Comment by evbo** [comment]
@astonbitecode and lastly, are these channels bi-directional as well? Or can Rust only receive?

Or, if I can guarantee the long running process outlives all callbacks, is there any way possible to invoke the instance again?

The reason is after the long running process consumes the instance, I still need the option of cancelling the long running process cleanly and ideally would be able to call another method.

**Comment by astonbitecode** [comment]
You receive via the `Receiver` of an [mpsc channel](https://doc.rust-lang.org/std/sync/mpsc/index.html). You may see in the rust docs how the channel is working, how it can be closed etc.

You may not send via a `Receiver`.

**Comment by evbo** [comment]
ah okay I think I get it: Don't move the instance to a new thread, instead just create as many channels as needed with the instance.

**Comment by astonbitecode** [comment]
> Don't move the instance to a new thread

If you mean a `InstanceReceiver`, then yes  you cannot send it to other threads.

However, a normal `Instance` __can__ be sent to other threads because it implements the `Send` trait.

**Comment by evbo** [comment]
right, but `&Instance` I thought did not implement `Send`, and so what I'm saying is when you `move` it to a new thread (like [here](https://github.com/astonbitecode/j4rs/blob/aa33052ed0a45937d2372d636e8f45ad6a807e97/rust/src/lib.rs#L636)) you can't then use it in any other thread.

**Comment by astonbitecode** [comment]
Yes, `&Instance` is not `Send`. If it was, then `Instance` would be `Sync` ([source](https://doc.rust-lang.org/nomicon/send-and-sync.html#send-and-sync)). But it is not; it is only `Send`, but not `Sync`.

**Comment by evbo** [comment]
So how can I orchestrate multiple asychronous calls to a single `Instance`?

I need to first fire and forget a long running instance method, then asychronously receive callbacks - receiver is perfect for that

Then at any point I need to call an instance method synchronously, which will gracefully stop the long running method

**Comment by astonbitecode** [comment]
It's up to you. You could orchestrate this in the Java world for example.

In each thread you should have a separate `Jvm` (Jvm is not send either because the underlying JNI `JNIEnv` needs to be [attached to a thread](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html#attaching_to_the_vm)). 

Then, in each thread, you could create one channel by calling the Java object you want and getting an `InstanceReceiver`.

**Comment by evbo** [comment]
> Then, in each thread, you could create one channel by calling the Java object you want (the same Java Object) and getting an InstanceReceiver.

But this is where it's not clear because after I `move` an `Instance` into a thread I can't `move` it also anywhere else. I could do this with `Arc<Instance>`, that there's no `Send` for that. Are you suggesting I create a newtype that implements `Send` for an Arc or some wrapper class?
