### ISSUE TITLE
Java class with $ is not a valid identifier

### ISSUE THREAD

**Issue by sbrunk** [astonbitecode/j4rs#57]
When defining a native method inside a Scala singleton object like so:

```scala
object Tokenizer {
  @native
  def fromPretrained(identifier: Instance[String]): Instance[Long]
}
```

The Scala compiler synthesizes a Java class with the following signature:
```java
public final class Tokenizer$ implements java.io.Serializable {
...
```

Now using that from j4rs in a `call_from_java` macro
```rust
#[call_from_java("Tokenizer$.fromPretrained")]
fn from_pretrained(identifier: Instance) -> Result<Instance, String> {
...
```
 results in the following error:
```
custom attribute panicked
message: `"Java_io_brunk_tokenizers_j4rs_Tokenizer$_fromPretrained"` is not a valid identifier
```

I'm still new to 4jrs and Rust in general so I might be completely wrong, but I believe the panic is caused when creating an  [Ident](https://doc.rust-lang.org/proc_macro/struct.Ident.html) in `j4rs_derive` because due to the $ it is not a valid rust identifier.
```
let ref jni_ident = Ident::new(jni_ident_string.as_ref(), Span::call_site());
```

Any idea if there's a way to make this work on the rust side?

**Comment by astonbitecode** [comment]
Unfortunately `$` is not allowed in expressions yet.

There is an [RFC](https://github.com/rust-lang/rfcs/blob/master/text/3086-macro-metavar-expr.md), which tries to expand `$$`  to a single `$` but as far as I understand, it applies only to `macro_rules!`...

I tried using nightly and add `#![feature(macro_metavar_expr)]` but still got the same error.

It's been some time I haven't dealt with Scala, but, can't you call the native code from a class instead of an object? Does the class still add `$`?

If yes, I am afraid you should have Scala calling Java to call Rust, which is maybe a bit of a hassle.

**Comment by sbrunk** [comment]
Thanks for your help @astonbitecode

Yes using a Scala class works, but Scala does not have `static` methods (because of its first class singletons) so I'd need to instantiate an object.

So I'm just using a Java class now with with static methods as you've also suggested. It can be compiled alongside the Scala code, so it's totally ok this way.

```java
public class NativeInterface {
  public static native Instance<Long> fromPretrained(Instance<String> identifier);
}
```

I think we can close this, since it is really just a minor annoyance, and there are simple workarounds.

**Comment by astonbitecode** [comment]
Thanks for the report!
