### ISSUE TITLE
Thread.currentThread().getContextClassLoader() null after first invocation

### ISSUE THREAD

**Issue by m0ppers** [astonbitecode/j4rs#60]
I am not sure if I am doing something wrong or if this is a bug. I have a minimalish testrepo here: https://github.com/m0ppers/j4rs-test

I have implemented two simple tests which are doing exactly the same. When I run `J4RS_CONSOLE_LOG_LEVEL=debug cargo test` the first testcase works. The second testcase tries to reuse the existing jvm but in there `Thread.currentThread().getContextClassLoader()` is null.

I am not sure if I am missing something. I am not really into Java and I don't know what the library I am using (in my real scenario) is doing with this ContextClassLoader but to me this seems like a bug? I would expect this to work (but again - I might have missed something)

**Comment by astonbitecode** [comment]
It seems that the first `Jvm` creation and execution succeeds because the Java code runs on the main thread, which actually created the JVM. 

The second thread is not the main one and `j4rs` attaches the JVM to the new thread using [AttachCurrentThread](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html#AttachCurrentThread). However, the specification says for `AttachCurrentThread`:

> When a thread is attached to the VM, the context class loader is the bootstrap loader.

So, the ContextClassloader of the thread is not the System Classloader. 

I am [reading on SO](https://stackoverflow.com/a/29194820) that this can be explicitly fixed if you do:

```java
java.lang.Thread.currentThread().setContextClassLoader(
    java.lang.ClassLoader.getSystemClassLoader()
);
```

on the spawned thread.

Can you see if this helps?

**Comment by m0ppers** [comment]
I really should have googled a bit more :see_no_evil: sorry

Your suggestion indeed solved the problem :partying_face: thank you

**Comment by astonbitecode** [comment]
Glad it worked @m0ppers . 

Just to add that you could also do this in Rust code if you don't want to write Java:

```rust
        let jvm = JvmBuilder::new().build()?;

        // Java code: java.lang.ClassLoader.getSystemClassLoader()
        let system_classloader = jvm.invoke_static("java.lang.ClassLoader", "getSystemClassLoader", &[])?;

        // Java code: java.lang.Thread.currentThread().setContextClassLoader(...)
        let thread_static_handle = jvm.static_class("java.lang.Thread")?;
        jvm.chain(&thread_static_handle)?
            .invoke("currentThread", &[])?
            .invoke("setContextClassLoader", &[InvocationArg::from(system_classloader)])?;
```
