### ISSUE TITLE
Feature request: variants with different android serialize/deserialize library

### ISSUE THREAD

**Issue by XizhiXu** [astonbitecode/j4rs#62]
Hey @astonbitecode,

Thanks for the recent update for Android, it is working great!

But we ususally use **gson** or **moshi** instead of **jackson** in Android to serialize and deserialize. Do you think it's possible to publish a variant with those libraries? Or can we have some config to instruct the `JsonValueFactory` to create `JsonValue` with a different implement?

**Comment by astonbitecode** [comment]
Hi @XizhiXu. 

Is using jackson an actual problem like eg. clashing of classnames etc? Or is it a matter of choice in terms of speed, specific security features etc?

**Comment by XizhiXu** [comment]
Oh jackson itself is good. 

For our current status, The concern is mainly about the size. Since we already have a serialize/deserialize library, we'd like to keep it consistent. Another concern is the speed because it uses reflection while we use **moshi** adapter. But this is minor.

**Comment by astonbitecode** [comment]
Hi @XizhiXu. The feature is implemented using the [Service Provider Interface](https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html). 

If anyone wants, they may configure `j4rs` to handle ser/deserialization, using a service provided via SPI - that is, providing an implementation of `org.astonbitecode.j4rs.api.services.json.Codec`.

I added one example in the [j4rs-java-call-rust](https://github.com/astonbitecode/j4rs-java-call-rust) repository. In order to check this out:

1. Change the [Main](https://github.com/astonbitecode/j4rs-java-call-rust/blob/b37c9365c1b361b66ddb68084f55718a08f574a9/java/src/main/java/io/github/astonbitecode/j4rs/example/Main.java#L21) to use the [doCallWithCustomClass](https://github.com/astonbitecode/j4rs-java-call-rust/blob/b37c9365c1b361b66ddb68084f55718a08f574a9/java/src/main/java/io/github/astonbitecode/j4rs/example/RustFunctionCalls.java#L73) method of `RustFunctionCalls` class.
2. Remove the `#` to uncomment the line in the [service file in META-INF](https://github.com/astonbitecode/j4rs-java-call-rust/blob/b37c9365c1b361b66ddb68084f55718a08f574a9/java/src/main/resources/META-INF/services/org.astonbitecode.j4rs.api.services.json.Codec#L1).
3. Run the application. You may see that the ser/deserialization is done using the [MyClassJsonCodec](https://github.com/astonbitecode/j4rs-java-call-rust/blob/b37c9365c1b361b66ddb68084f55718a08f574a9/java/src/main/java/io/github/astonbitecode/j4rs/example/json/MyClassJsonCodec.java#L24).

Additionally, since one of your concerns was the size, you may [exclude the jackson transitive dependencies of `j4rs`](https://github.com/astonbitecode/j4rs-java-call-rust/blob/b37c9365c1b361b66ddb68084f55718a08f574a9/java/pom.xml#L23).

**Comment by XizhiXu** [comment]
Thank you some much for your quick update! That is awesome. Could you please publish this change? Otherwise, we need to test with the dependency of the project instead of the binary artifact.

**Comment by astonbitecode** [comment]
Sure, I can publish the change in the next days. I was hoping you could give it a try and see if it works for you too. 

Anyhow, I have tested it with Android too and works flawlessly. If there is no ability to test it on your side, please tell me to proceed with publishing.

**Comment by astonbitecode** [comment]
Thanks @XizhiXu for the PR and for taking the time to test this! 

This will be released soon.
