### ISSUE TITLE
`J4rsClassLoader` The constructor URLClassLoader(String, URL[], ClassLoader) is undefined

### ISSUE THREAD

**Issue by artshell** [astonbitecode/j4rs#77]
```java
    public J4rsClassLoader(ClassLoader offeredClassLoader) {
        super("j4rsClassLoader", new URL[0], offeredClassLoader);
    }
```
[The constructor URLClassLoader(String, URL[], ClassLoader) is undefined](https://github.com/astonbitecode/j4rs/blob/d352874170829172a44bc27002a67236a0c4610c/java/src/main/java/org/astonbitecode/j4rs/api/deploy/J4rsClassLoader.java#L22)

After change like following:
```java
    public J4rsClassLoader(ClassLoader offeredClassLoader) {
        super(new URL[0], offeredClassLoader);
    }
```

**Comment by astonbitecode** [comment]
What is the issue? Please note that you need Java 11 to build `j4rs` because of the JavaFX bits. Also, if  you want to use `j4rs` with Java 8, this is still supported, as described [here](https://github.com/astonbitecode/j4rs#i-get-javalangnosuchmethoderror-javaneturlclassloaderinitljavalangstringljavaneturlljavalangclassloaderv).

**Comment by artshell** [comment]
thanks!
