### ISSUE TITLE
How to call channel  from Java to rust

### ISSUE THREAD

**Issue by Swibon96** [astonbitecode/j4rs#79]

**Comment by astonbitecode** [comment]
Please provide more info for the question.

Long shot, do you mean [this](https://github.com/astonbitecode/j4rs#Callback-support)?

**Comment by Swibon96** [comment]
Actually,when I create the InvocationArg，I cannot pass a channel（e.g.，flume::Receiver<T> ） type as a parameter to java, So，how do I interact with it directly from Java?

**Comment by astonbitecode** [comment]
You cannot pass Rust constructs as arguments to Java. Java does not know what a `flume::Receiver` is. 

Passing basic Rust constructs like `i32`, `String`s etc is possible because `j4rs` actually has `TryFrom` implementations for them and they are actually transformed to the respective Java ones.
Custom objects (ie. structs in Rust), can be sent to Java after being serialized, but this needs Java to be able to deserialize these to actual known Java objects.

I would propose to re-think what you try to achieve.

**Comment by Swibon96** [comment]
Sorry to bother you again.

when I tried to run the following code.
`    async fn iteration(&self) -> Result<()> {
        let ja = &self.state.ja;
        let (message, _) = self.inputs.recv().await?;
        if let Message::Data(characters) = message { 
            let data = characters.as_str();
            let ja_data = InvocationArg::try_from(data)?;
            let s_m = ja.invoke(&self.state.ja_state, "iteration", &[ja_data])?;
            let s_mm:String = ja.to_rust(s_m)?;
            return self.outputs.send(data.as_bytes(), None).await;
        }
        Ok(())
    }`

 I encountered this error:
`error: future cannot be sent between threads safely
   --> zenoh-flow-java-operator-wrapper\src/lib.rs:128:45
    |
128 |       async fn iteration(&self) -> Result<()> {
    |  _____________________________________________^
129 | |         let ja = &self.state.ja;
130 | |
131 | |         let (message, _) = self.inputs.recv().await?;
...   |
140 | |         Ok(())
141 | |     }
    | |_____^ future created by async block is not `Send`
    |
    = help: within `Jvm`, the trait `Sync` is not implemented for `*mut *const JNINativeInterface_`
note: future is not `Send` as this value is used across an await
   --> zenoh-flow-java-operator-wrapper\src/lib.rs:131:47
    |
129 |         let ja = &self.state.ja;
    |                   ------------- has type `Arc<Jvm>` which is not `Send`
130 |
131 |         let (message, _) = self.inputs.recv().await?;
    |                                               ^^^^^ await occurs here, with `self.state.ja` maybe used later
...
141 |     }
    |     - `self.state.ja` is later dropped here
    = note: required for the cast from `Pin<Box<[async block@zenoh-flow-java-operator-wrapper\src/lib.rs:128:45: 141:6]>>` to `Pin<Box<(dyn Future<Output = Result<(), Box<(dyn std::error::Error + Send + Sync + 'static)>>> + Send + 'async_trait)>>`
`

**Comment by Swibon96** [comment]
>     async fn iteration(&self) -> Result<()> {
        let ja = &self.state.ja;

        let (message, _) = self.inputs.recv().await?;
        if let Message::Data(characters) = message { 

            let data = characters.as_str();
            let ja_data = InvocationArg::try_from(data)?;
            let s_m = ja.invoke(&self.state.ja_state, "iteration", &[ja_data])?;
            let s_mm:String = ja.to_rust(s_m)?;
            return self.outputs.send(data.as_bytes(), None).await;
        }
        Ok(())
    }

**Comment by astonbitecode** [comment]
This is because the `Jvm` is not `Send` and cannot be shared between threads. You should remove the `ja` from the `state` and create a new `Jvm` after `await`ing the future. 

Please have a look at [this comment](https://github.com/astonbitecode/j4rs/issues/72#issuecomment-1700477909) for more info.

**Comment by astonbitecode** [comment]
I guess we can close this now...
