### ISSUE TITLE
Ability to define alternative and/or additional Maven repositories

### ISSUE THREAD

**Issue by jacaetevha** [astonbitecode/j4rs#8]
Would it be feasible to support multiple, or simply a single alternative Maven repo when defining a `MavenArtifact`.

Perhaps something like this for a single alternative:

```rust
let proprietary_artifact = MavenArtifact::from("org.my.company:MyArtifact:1.0.0", "https://company.org/artifactory/repo");
jvm.deploy_maven(proprietary_artifact).unwrap();
```

Perhaps something like this for multiple alternatives:

```rust
let proprietary_artifact = MavenArtifact::from("org.my.company:MyArtifact:1.0.0", vec!["https://company.org/artifactory/repo", "mavenLocal", "https://jcenter.bintray.com", "mavenCentral"]);
jvm.deploy_maven(proprietary_artifact).unwrap();
```

**Comment by astonbitecode** [comment]
There were plans to implement that in a future release, so, yes alternative repos will be supported for sure.

**Comment by astonbitecode** [comment]
The feature is now in the master. 

In order to specify more Maven repositories, use the `JvmBuilder.with_maven_settings` method.
This takes a `MavenSettings` argument, which currently contains a vec of `MavenArtifactRepo`s.
Each repo has its _id_ and _uri_ and there is a `From` implementation for them.

For example:

```rust
let jvm: Jvm = JvmBuilder::new()
   .with_maven_settings(MavenSettings::new(vec![
      MavenArtifactRepo::from("myrepo1::https://my.repo.io/artifacts"),
      MavenArtifactRepo::from("myrepo2::https://my.other.repo.io/artifacts")])
   )
   .build()
   .unwrap();

   assert!(jvm.deploy_artifact(&MavenArtifact::from("io.github.astonbitecode:j4rs:0.5.1")).is_ok());
```

Please note that the Maven central is always included in the searches.

If you have any issues or suggestions, please comment.

**Comment by jacaetevha** [comment]
That's great. Will give it a go.

**Comment by astonbitecode** [comment]
You may now use [v0.9.0](https://crates.io/crates/j4rs).
